package com.ssm.bean;

import java.util.Date;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.classId
     *
     * @mbg.generated
     */
    private String classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.courseTypeId
     *
     * @mbg.generated
     */
    private String coursetypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.beginTime
     *
     * @mbg.generated
     */
    private Date begintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.endTime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.totalCount
     *
     * @mbg.generated
     */
    private Integer totalcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.upgradeCount
     *
     * @mbg.generated
     */
    private Integer upgradecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.changeCount
     *
     * @mbg.generated
     */
    private Integer changecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.runoffCount
     *
     * @mbg.generated
     */
    private Integer runoffcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.uploadFile
     *
     * @mbg.generated
     */
    private String uploadfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.uploadTime
     *
     * @mbg.generated
     */
    private Date uploadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.uploadPath
     *
     * @mbg.generated
     */
    private String uploadpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_class.uploadFilename
     *
     * @mbg.generated
     */
    private String uploadfilename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.classId
     *
     * @return the value of crm_class.classId
     *
     * @mbg.generated
     */
    public String getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.classId
     *
     * @param classid the value for crm_class.classId
     *
     * @mbg.generated
     */
    public void setClassid(String classid) {
        this.classid = classid == null ? null : classid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.courseTypeId
     *
     * @return the value of crm_class.courseTypeId
     *
     * @mbg.generated
     */
    public String getCoursetypeid() {
        return coursetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.courseTypeId
     *
     * @param coursetypeid the value for crm_class.courseTypeId
     *
     * @mbg.generated
     */
    public void setCoursetypeid(String coursetypeid) {
        this.coursetypeid = coursetypeid == null ? null : coursetypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.name
     *
     * @return the value of crm_class.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.name
     *
     * @param name the value for crm_class.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.beginTime
     *
     * @return the value of crm_class.beginTime
     *
     * @mbg.generated
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.beginTime
     *
     * @param begintime the value for crm_class.beginTime
     *
     * @mbg.generated
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.endTime
     *
     * @return the value of crm_class.endTime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.endTime
     *
     * @param endtime the value for crm_class.endTime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.status
     *
     * @return the value of crm_class.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.status
     *
     * @param status the value for crm_class.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.totalCount
     *
     * @return the value of crm_class.totalCount
     *
     * @mbg.generated
     */
    public Integer getTotalcount() {
        return totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.totalCount
     *
     * @param totalcount the value for crm_class.totalCount
     *
     * @mbg.generated
     */
    public void setTotalcount(Integer totalcount) {
        this.totalcount = totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.upgradeCount
     *
     * @return the value of crm_class.upgradeCount
     *
     * @mbg.generated
     */
    public Integer getUpgradecount() {
        return upgradecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.upgradeCount
     *
     * @param upgradecount the value for crm_class.upgradeCount
     *
     * @mbg.generated
     */
    public void setUpgradecount(Integer upgradecount) {
        this.upgradecount = upgradecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.changeCount
     *
     * @return the value of crm_class.changeCount
     *
     * @mbg.generated
     */
    public Integer getChangecount() {
        return changecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.changeCount
     *
     * @param changecount the value for crm_class.changeCount
     *
     * @mbg.generated
     */
    public void setChangecount(Integer changecount) {
        this.changecount = changecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.runoffCount
     *
     * @return the value of crm_class.runoffCount
     *
     * @mbg.generated
     */
    public Integer getRunoffcount() {
        return runoffcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.runoffCount
     *
     * @param runoffcount the value for crm_class.runoffCount
     *
     * @mbg.generated
     */
    public void setRunoffcount(Integer runoffcount) {
        this.runoffcount = runoffcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.remark
     *
     * @return the value of crm_class.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.remark
     *
     * @param remark the value for crm_class.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.uploadFile
     *
     * @return the value of crm_class.uploadFile
     *
     * @mbg.generated
     */
    public String getUploadfile() {
        return uploadfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.uploadFile
     *
     * @param uploadfile the value for crm_class.uploadFile
     *
     * @mbg.generated
     */
    public void setUploadfile(String uploadfile) {
        this.uploadfile = uploadfile == null ? null : uploadfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.uploadTime
     *
     * @return the value of crm_class.uploadTime
     *
     * @mbg.generated
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.uploadTime
     *
     * @param uploadtime the value for crm_class.uploadTime
     *
     * @mbg.generated
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.uploadPath
     *
     * @return the value of crm_class.uploadPath
     *
     * @mbg.generated
     */
    public String getUploadpath() {
        return uploadpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.uploadPath
     *
     * @param uploadpath the value for crm_class.uploadPath
     *
     * @mbg.generated
     */
    public void setUploadpath(String uploadpath) {
        this.uploadpath = uploadpath == null ? null : uploadpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_class.uploadFilename
     *
     * @return the value of crm_class.uploadFilename
     *
     * @mbg.generated
     */
    public String getUploadfilename() {
        return uploadfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_class.uploadFilename
     *
     * @param uploadfilename the value for crm_class.uploadFilename
     *
     * @mbg.generated
     */
    public void setUploadfilename(String uploadfilename) {
        this.uploadfilename = uploadfilename == null ? null : uploadfilename.trim();
    }

    @Override
    public String toString() {
        return "Class{" +
                "classid='" + classid + '\'' +
                ", coursetypeid='" + coursetypeid + '\'' +
                ", name='" + name + '\'' +
                ", begintime=" + begintime +
                ", endtime=" + endtime +
                ", status='" + status + '\'' +
                ", totalcount=" + totalcount +
                ", upgradecount=" + upgradecount +
                ", changecount=" + changecount +
                ", runoffcount=" + runoffcount +
                ", remark='" + remark + '\'' +
                ", uploadfile='" + uploadfile + '\'' +
                ", uploadtime=" + uploadtime +
                ", uploadpath='" + uploadpath + '\'' +
                ", uploadfilename='" + uploadfilename + '\'' +
                '}';
    }
}