package com.ssm.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_department.depId
     *
     * @mbg.generated
     */
    private String depid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_department.depName
     *
     * @mbg.generated
     */
    private String depname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_department.depId
     *
     * @return the value of crm_department.depId
     *
     * @mbg.generated
     */
    public String getDepid() {
        return depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_department.depId
     *
     * @param depid the value for crm_department.depId
     *
     * @mbg.generated
     */
    public void setDepid(String depid) {
        this.depid = depid == null ? null : depid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_department.depName
     *
     * @return the value of crm_department.depName
     *
     * @mbg.generated
     */
    public String getDepname() {
        return depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_department.depName
     *
     * @param depname the value for crm_department.depName
     *
     * @mbg.generated
     */
    public void setDepname(String depname) {
        this.depname = depname == null ? null : depname.trim();
    }
}