package com.ssm.bean;

import java.util.Date;

public class Graduate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_graduate.granduateId
     *
     * @mbg.generated
     */
    private String granduateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_graduate.studentId
     *
     * @mbg.generated
     */
    private String studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_graduate.companyName
     *
     * @mbg.generated
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_graduate.salary
     *
     * @mbg.generated
     */
    private String salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_graduate.post
     *
     * @mbg.generated
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_graduate.entryTime
     *
     * @mbg.generated
     */
    private Date entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_graduate.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_graduate.classId
     *
     * @mbg.generated
     */
    private String classid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_graduate.granduateId
     *
     * @return the value of crm_graduate.granduateId
     *
     * @mbg.generated
     */
    public String getGranduateid() {
        return granduateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_graduate.granduateId
     *
     * @param granduateid the value for crm_graduate.granduateId
     *
     * @mbg.generated
     */
    public void setGranduateid(String granduateid) {
        this.granduateid = granduateid == null ? null : granduateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_graduate.studentId
     *
     * @return the value of crm_graduate.studentId
     *
     * @mbg.generated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_graduate.studentId
     *
     * @param studentid the value for crm_graduate.studentId
     *
     * @mbg.generated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_graduate.companyName
     *
     * @return the value of crm_graduate.companyName
     *
     * @mbg.generated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_graduate.companyName
     *
     * @param companyname the value for crm_graduate.companyName
     *
     * @mbg.generated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_graduate.salary
     *
     * @return the value of crm_graduate.salary
     *
     * @mbg.generated
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_graduate.salary
     *
     * @param salary the value for crm_graduate.salary
     *
     * @mbg.generated
     */
    public void setSalary(String salary) {
        this.salary = salary == null ? null : salary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_graduate.post
     *
     * @return the value of crm_graduate.post
     *
     * @mbg.generated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_graduate.post
     *
     * @param post the value for crm_graduate.post
     *
     * @mbg.generated
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_graduate.entryTime
     *
     * @return the value of crm_graduate.entryTime
     *
     * @mbg.generated
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_graduate.entryTime
     *
     * @param entrytime the value for crm_graduate.entryTime
     *
     * @mbg.generated
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_graduate.remark
     *
     * @return the value of crm_graduate.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_graduate.remark
     *
     * @param remark the value for crm_graduate.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_graduate.classId
     *
     * @return the value of crm_graduate.classId
     *
     * @mbg.generated
     */
    public String getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_graduate.classId
     *
     * @param classid the value for crm_graduate.classId
     *
     * @mbg.generated
     */
    public void setClassid(String classid) {
        this.classid = classid == null ? null : classid.trim();
    }
}