package com.ssm.bean;

import java.util.Date;

public class Outflow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_outflow.runOffId
     *
     * @mbg.generated
     */
    private String runoffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_outflow.studentId
     *
     * @mbg.generated
     */
    private String studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_outflow.staffId
     *
     * @mbg.generated
     */
    private String staffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_outflow.createDate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_outflow.isRefund
     *
     * @mbg.generated
     */
    private String isrefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_outflow.refundAmount
     *
     * @mbg.generated
     */
    private String refundamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_outflow.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_outflow.runOffId
     *
     * @return the value of crm_outflow.runOffId
     *
     * @mbg.generated
     */
    public String getRunoffid() {
        return runoffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_outflow.runOffId
     *
     * @param runoffid the value for crm_outflow.runOffId
     *
     * @mbg.generated
     */
    public void setRunoffid(String runoffid) {
        this.runoffid = runoffid == null ? null : runoffid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_outflow.studentId
     *
     * @return the value of crm_outflow.studentId
     *
     * @mbg.generated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_outflow.studentId
     *
     * @param studentid the value for crm_outflow.studentId
     *
     * @mbg.generated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_outflow.staffId
     *
     * @return the value of crm_outflow.staffId
     *
     * @mbg.generated
     */
    public String getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_outflow.staffId
     *
     * @param staffid the value for crm_outflow.staffId
     *
     * @mbg.generated
     */
    public void setStaffid(String staffid) {
        this.staffid = staffid == null ? null : staffid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_outflow.createDate
     *
     * @return the value of crm_outflow.createDate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_outflow.createDate
     *
     * @param createdate the value for crm_outflow.createDate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_outflow.isRefund
     *
     * @return the value of crm_outflow.isRefund
     *
     * @mbg.generated
     */
    public String getIsrefund() {
        return isrefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_outflow.isRefund
     *
     * @param isrefund the value for crm_outflow.isRefund
     *
     * @mbg.generated
     */
    public void setIsrefund(String isrefund) {
        this.isrefund = isrefund == null ? null : isrefund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_outflow.refundAmount
     *
     * @return the value of crm_outflow.refundAmount
     *
     * @mbg.generated
     */
    public String getRefundamount() {
        return refundamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_outflow.refundAmount
     *
     * @param refundamount the value for crm_outflow.refundAmount
     *
     * @mbg.generated
     */
    public void setRefundamount(String refundamount) {
        this.refundamount = refundamount == null ? null : refundamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_outflow.remark
     *
     * @return the value of crm_outflow.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_outflow.remark
     *
     * @param remark the value for crm_outflow.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}