package com.ssm.bean;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_post.postId
     *
     * @mbg.generated
     */
    private String postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_post.postName
     *
     * @mbg.generated
     */
    private String postname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_post.depId
     *
     * @mbg.generated
     */
    private String depid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_post.postId
     *
     * @return the value of crm_post.postId
     *
     * @mbg.generated
     */
    public String getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_post.postId
     *
     * @param postid the value for crm_post.postId
     *
     * @mbg.generated
     */
    public void setPostid(String postid) {
        this.postid = postid == null ? null : postid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_post.postName
     *
     * @return the value of crm_post.postName
     *
     * @mbg.generated
     */
    public String getPostname() {
        return postname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_post.postName
     *
     * @param postname the value for crm_post.postName
     *
     * @mbg.generated
     */
    public void setPostname(String postname) {
        this.postname = postname == null ? null : postname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_post.depId
     *
     * @return the value of crm_post.depId
     *
     * @mbg.generated
     */
    public String getDepid() {
        return depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_post.depId
     *
     * @param depid the value for crm_post.depId
     *
     * @mbg.generated
     */
    public void setDepid(String depid) {
        this.depid = depid == null ? null : depid.trim();
    }
}