package com.ssm.bean;

import java.util.Date;

public class Refer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.referId
     *
     * @mbg.generated
     */
    private String referid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.createDate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.staffId
     *
     * @mbg.generated
     */
    private String staffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.intentionLevel
     *
     * @mbg.generated
     */
    private String intentionlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.classId
     *
     * @mbg.generated
     */
    private String classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.courseTypeId
     *
     * @mbg.generated
     */
    private String coursetypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_refer.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.referId
     *
     * @return the value of crm_refer.referId
     *
     * @mbg.generated
     */
    public String getReferid() {
        return referid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.referId
     *
     * @param referid the value for crm_refer.referId
     *
     * @mbg.generated
     */
    public void setReferid(String referid) {
        this.referid = referid == null ? null : referid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.name
     *
     * @return the value of crm_refer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.name
     *
     * @param name the value for crm_refer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.telephone
     *
     * @return the value of crm_refer.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.telephone
     *
     * @param telephone the value for crm_refer.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.qq
     *
     * @return the value of crm_refer.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.qq
     *
     * @param qq the value for crm_refer.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.createDate
     *
     * @return the value of crm_refer.createDate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.createDate
     *
     * @param createdate the value for crm_refer.createDate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.staffId
     *
     * @return the value of crm_refer.staffId
     *
     * @mbg.generated
     */
    public String getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.staffId
     *
     * @param staffid the value for crm_refer.staffId
     *
     * @mbg.generated
     */
    public void setStaffid(String staffid) {
        this.staffid = staffid == null ? null : staffid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.intentionLevel
     *
     * @return the value of crm_refer.intentionLevel
     *
     * @mbg.generated
     */
    public String getIntentionlevel() {
        return intentionlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.intentionLevel
     *
     * @param intentionlevel the value for crm_refer.intentionLevel
     *
     * @mbg.generated
     */
    public void setIntentionlevel(String intentionlevel) {
        this.intentionlevel = intentionlevel == null ? null : intentionlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.classId
     *
     * @return the value of crm_refer.classId
     *
     * @mbg.generated
     */
    public String getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.classId
     *
     * @param classid the value for crm_refer.classId
     *
     * @mbg.generated
     */
    public void setClassid(String classid) {
        this.classid = classid == null ? null : classid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.courseTypeId
     *
     * @return the value of crm_refer.courseTypeId
     *
     * @mbg.generated
     */
    public String getCoursetypeid() {
        return coursetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.courseTypeId
     *
     * @param coursetypeid the value for crm_refer.courseTypeId
     *
     * @mbg.generated
     */
    public void setCoursetypeid(String coursetypeid) {
        this.coursetypeid = coursetypeid == null ? null : coursetypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.source
     *
     * @return the value of crm_refer.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.source
     *
     * @param source the value for crm_refer.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.status
     *
     * @return the value of crm_refer.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.status
     *
     * @param status the value for crm_refer.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_refer.remark
     *
     * @return the value of crm_refer.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_refer.remark
     *
     * @param remark the value for crm_refer.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}