package com.ssm.bean;

import java.util.Date;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_staff.staffId
     *
     * @mbg.generated
     */
    private String staffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_staff.loginName
     *
     * @mbg.generated
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_staff.loginPwd
     *
     * @mbg.generated
     */
    private String loginpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_staff.staffName
     *
     * @mbg.generated
     */
    private String staffname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_staff.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_staff.onDutyDate
     *
     * @mbg.generated
     */
    private Date ondutydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_staff.postId
     *
     * @mbg.generated
     */
    private String postid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_staff.staffId
     *
     * @return the value of crm_staff.staffId
     *
     * @mbg.generated
     */
    public String getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_staff.staffId
     *
     * @param staffid the value for crm_staff.staffId
     *
     * @mbg.generated
     */
    public void setStaffid(String staffid) {
        this.staffid = staffid == null ? null : staffid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_staff.loginName
     *
     * @return the value of crm_staff.loginName
     *
     * @mbg.generated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_staff.loginName
     *
     * @param loginname the value for crm_staff.loginName
     *
     * @mbg.generated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_staff.loginPwd
     *
     * @return the value of crm_staff.loginPwd
     *
     * @mbg.generated
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_staff.loginPwd
     *
     * @param loginpwd the value for crm_staff.loginPwd
     *
     * @mbg.generated
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_staff.staffName
     *
     * @return the value of crm_staff.staffName
     *
     * @mbg.generated
     */
    public String getStaffname() {
        return staffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_staff.staffName
     *
     * @param staffname the value for crm_staff.staffName
     *
     * @mbg.generated
     */
    public void setStaffname(String staffname) {
        this.staffname = staffname == null ? null : staffname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_staff.gender
     *
     * @return the value of crm_staff.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_staff.gender
     *
     * @param gender the value for crm_staff.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_staff.onDutyDate
     *
     * @return the value of crm_staff.onDutyDate
     *
     * @mbg.generated
     */
    public Date getOndutydate() {
        return ondutydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_staff.onDutyDate
     *
     * @param ondutydate the value for crm_staff.onDutyDate
     *
     * @mbg.generated
     */
    public void setOndutydate(Date ondutydate) {
        this.ondutydate = ondutydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_staff.postId
     *
     * @return the value of crm_staff.postId
     *
     * @mbg.generated
     */
    public String getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_staff.postId
     *
     * @param postid the value for crm_staff.postId
     *
     * @mbg.generated
     */
    public void setPostid(String postid) {
        this.postid = postid == null ? null : postid.trim();
    }
}