package com.ssm.bean;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.studentId
     *
     * @mbg.generated
     */
    private String studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.mustTuition
     *
     * @mbg.generated
     */
    private Integer musttuition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.actualTuition
     *
     * @mbg.generated
     */
    private Integer actualtuition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.identity
     *
     * @mbg.generated
     */
    private String identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.classId
     *
     * @mbg.generated
     */
    private String classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.education
     *
     * @mbg.generated
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.professional
     *
     * @mbg.generated
     */
    private String professional;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.identityAddress
     *
     * @mbg.generated
     */
    private String identityaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.homeTelephone
     *
     * @mbg.generated
     */
    private String hometelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.homeUser
     *
     * @mbg.generated
     */
    private String homeuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_student.referId
     *
     * @mbg.generated
     */
    private String referid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.studentId
     *
     * @return the value of crm_student.studentId
     *
     * @mbg.generated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.studentId
     *
     * @param studentid the value for crm_student.studentId
     *
     * @mbg.generated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.name
     *
     * @return the value of crm_student.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.name
     *
     * @param name the value for crm_student.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.gender
     *
     * @return the value of crm_student.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.gender
     *
     * @param gender the value for crm_student.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.mustTuition
     *
     * @return the value of crm_student.mustTuition
     *
     * @mbg.generated
     */
    public Integer getMusttuition() {
        return musttuition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.mustTuition
     *
     * @param musttuition the value for crm_student.mustTuition
     *
     * @mbg.generated
     */
    public void setMusttuition(Integer musttuition) {
        this.musttuition = musttuition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.actualTuition
     *
     * @return the value of crm_student.actualTuition
     *
     * @mbg.generated
     */
    public Integer getActualtuition() {
        return actualtuition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.actualTuition
     *
     * @param actualtuition the value for crm_student.actualTuition
     *
     * @mbg.generated
     */
    public void setActualtuition(Integer actualtuition) {
        this.actualtuition = actualtuition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.telephone
     *
     * @return the value of crm_student.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.telephone
     *
     * @param telephone the value for crm_student.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.identity
     *
     * @return the value of crm_student.identity
     *
     * @mbg.generated
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.identity
     *
     * @param identity the value for crm_student.identity
     *
     * @mbg.generated
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.classId
     *
     * @return the value of crm_student.classId
     *
     * @mbg.generated
     */
    public String getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.classId
     *
     * @param classid the value for crm_student.classId
     *
     * @mbg.generated
     */
    public void setClassid(String classid) {
        this.classid = classid == null ? null : classid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.qq
     *
     * @return the value of crm_student.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.qq
     *
     * @param qq the value for crm_student.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.email
     *
     * @return the value of crm_student.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.email
     *
     * @param email the value for crm_student.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.school
     *
     * @return the value of crm_student.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.school
     *
     * @param school the value for crm_student.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.education
     *
     * @return the value of crm_student.education
     *
     * @mbg.generated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.education
     *
     * @param education the value for crm_student.education
     *
     * @mbg.generated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.professional
     *
     * @return the value of crm_student.professional
     *
     * @mbg.generated
     */
    public String getProfessional() {
        return professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.professional
     *
     * @param professional the value for crm_student.professional
     *
     * @mbg.generated
     */
    public void setProfessional(String professional) {
        this.professional = professional == null ? null : professional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.status
     *
     * @return the value of crm_student.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.status
     *
     * @param status the value for crm_student.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.identityAddress
     *
     * @return the value of crm_student.identityAddress
     *
     * @mbg.generated
     */
    public String getIdentityaddress() {
        return identityaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.identityAddress
     *
     * @param identityaddress the value for crm_student.identityAddress
     *
     * @mbg.generated
     */
    public void setIdentityaddress(String identityaddress) {
        this.identityaddress = identityaddress == null ? null : identityaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.address
     *
     * @return the value of crm_student.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.address
     *
     * @param address the value for crm_student.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.remark
     *
     * @return the value of crm_student.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.remark
     *
     * @param remark the value for crm_student.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.homeTelephone
     *
     * @return the value of crm_student.homeTelephone
     *
     * @mbg.generated
     */
    public String getHometelephone() {
        return hometelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.homeTelephone
     *
     * @param hometelephone the value for crm_student.homeTelephone
     *
     * @mbg.generated
     */
    public void setHometelephone(String hometelephone) {
        this.hometelephone = hometelephone == null ? null : hometelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.homeUser
     *
     * @return the value of crm_student.homeUser
     *
     * @mbg.generated
     */
    public String getHomeuser() {
        return homeuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.homeUser
     *
     * @param homeuser the value for crm_student.homeUser
     *
     * @mbg.generated
     */
    public void setHomeuser(String homeuser) {
        this.homeuser = homeuser == null ? null : homeuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_student.referId
     *
     * @return the value of crm_student.referId
     *
     * @mbg.generated
     */
    public String getReferid() {
        return referid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_student.referId
     *
     * @param referid the value for crm_student.referId
     *
     * @mbg.generated
     */
    public void setReferid(String referid) {
        this.referid = referid == null ? null : referid.trim();
    }
}